// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8-Du3gyqrBJfDqKZmcMOoQLhdLe1KBk',
    appId: '1:654375909575:web:7c241c223010f6bdb866e2',
    messagingSenderId: '654375909575',
    projectId: 'testing-firebase-26-1af1d',
    authDomain: 'testing-firebase-26-1af1d.firebaseapp.com',
    storageBucket: 'testing-firebase-26-1af1d.firebasestorage.app',
    measurementId: 'G-BY6K43SEF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8LWk6tVZ-tfRBBZAv1U_lOe0cI2j0U2Q',
    appId: '1:654375909575:android:172095279ca62a76b866e2',
    messagingSenderId: '654375909575',
    projectId: 'testing-firebase-26-1af1d',
    storageBucket: 'testing-firebase-26-1af1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbXqKGTe8Lry0UO17al8bQP_Drbhbj1k',
    appId: '1:654375909575:ios:6526e9cafb5c3b8ab866e2',
    messagingSenderId: '654375909575',
    projectId: 'testing-firebase-26-1af1d',
    storageBucket: 'testing-firebase-26-1af1d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbXqKGTe8Lry0UO17al8bQP_Drbhbj1k',
    appId: '1:654375909575:ios:6526e9cafb5c3b8ab866e2',
    messagingSenderId: '654375909575',
    projectId: 'testing-firebase-26-1af1d',
    storageBucket: 'testing-firebase-26-1af1d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
